// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM4IvQZtyoHwI_0lYcSSxqzax5xkJ2Bz4',
    appId: '1:5238107802:web:80b0e3ae734b69bf33b923',
    messagingSenderId: '5238107802',
    projectId: 'food-restaurant-app-1ea6e',
    authDomain: 'food-restaurant-app-1ea6e.firebaseapp.com',
    storageBucket: 'food-restaurant-app-1ea6e.firebasestorage.app',
    measurementId: 'G-MHE7X33M4X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWPUOtHAznMcW1UAYeVVKok22WXgJUshs',
    appId: '1:5238107802:android:2916b446302b16f533b923',
    messagingSenderId: '5238107802',
    projectId: 'food-restaurant-app-1ea6e',
    storageBucket: 'food-restaurant-app-1ea6e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgBwfBXoGZJ7aXmXtOvbM1xq4sdk3SFM0',
    appId: '1:5238107802:ios:75748849a2411bca33b923',
    messagingSenderId: '5238107802',
    projectId: 'food-restaurant-app-1ea6e',
    storageBucket: 'food-restaurant-app-1ea6e.firebasestorage.app',
    iosBundleId: 'com.app.downtown',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgBwfBXoGZJ7aXmXtOvbM1xq4sdk3SFM0',
    appId: '1:5238107802:ios:75748849a2411bca33b923',
    messagingSenderId: '5238107802',
    projectId: 'food-restaurant-app-1ea6e',
    storageBucket: 'food-restaurant-app-1ea6e.firebasestorage.app',
    iosBundleId: 'com.app.downtown',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDM4IvQZtyoHwI_0lYcSSxqzax5xkJ2Bz4',
    appId: '1:5238107802:web:205cab1a54c7e8c733b923',
    messagingSenderId: '5238107802',
    projectId: 'food-restaurant-app-1ea6e',
    authDomain: 'food-restaurant-app-1ea6e.firebaseapp.com',
    storageBucket: 'food-restaurant-app-1ea6e.firebasestorage.app',
    measurementId: 'G-ZWR9S841TP',
  );
}
